name: CI/CD

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to docker hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t elegance-jewellery-deploy .

      - name: Push docker image
        run: docker push pandadocked/elegance-jewellery-deploy

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull pandadocked/elegance-jewellery-deploy:latest
      - name: Run docker container
        run: docker run -d -p 8080:5137 -p 3000:3000 pandadocked/elegance-jewellery-deploy:latest